### ISSUE TITLE
Subscription-Issue2:  Allow event consumers to subscribe to more than one event types with a single subscription

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/Commonalities#154]
**Problem description**
Currently we expect the event consumers to create a subscription for each event type they want to consume. There are currently discussions in certain subprojects  https://github.com/camaraproject/DeviceLocation/issues/138#issuecomment-1894191964 which shows the need where allowing multiple types could offer better experience to the event consumers.

Camara could define a standard way to allow event consumers to subscribe to multiple event types using a subscription, instead of making the event consumer create a new subscription for every single event type.

The "types" array in CloudEvents subscription schema allows a consumer to specify the CloudEvent types eligible to be delivered by the subscription. 

**Possible evolution**
Subscription schema could be extended (as in cloudevents subscription) with "types"
<img width="575" alt="image" src="https://github.com/camaraproject/Commonalities/assets/77152136/8615e12e-c80e-4ab5-b497-e88a63337fec">

**Alternative solution**

**Additional context**
#149

**Comment by bigludo7** [comment]
Hello @shilpa-padgaonkar 
For subscription creation management (as a Telco I'm able to provide this one but not this one), subscription lifecycle management (management of `subscriptionMaxEvents` in this case), business model (how we manage the subscription should not impact the business model)  or for privacy/consent management (how we will be able to indicate that the user deny consent for one of the event type requested), I strongly prefer to keep it simple and stick the `type` to one.

Of course in future and with more developer feedbacks we can re-open this.

**Comment by shilpa-padgaonkar** [comment]
@bigludo7 : If I understood correctly, you are fine to use a common subscriptions API but would restrict it to offer just one event type.

If device status subproject (for discussion purpose would only have explicit subscriptions) then we would have 7 distinct API spec files (each spec file would include the subscription related content from the common subscriptions API ) for each of the below event types:

1. roaming-status
2. roaming-on 
3. roaming-off
4. change-country
5. connectivity-data
6. connectivity-sms
7. connectivity-disconnected 

Each of the above 7 API spec file would have a distinct API name. Is my understanding correct?

**Comment by akoshunyadi** [comment]
Distinct APIs we would only need if we need different scopes for the different types, right? Otherwise we can use all types in 1 API (in 1 scope).

This issue is also related to the possible filter parameter. If using that, we can define a more generic event types like roaming_status_changed & connectivity_status_changed, so we would have fewer event types per API.

**Comment by shilpa-padgaonkar** [comment]
@akoshunyadi : I am not sure I fully understand the comment.

In the device status API, (without subscriptions endpoint) there are 2 distinct scopes
- device-status:connectivity:read
- device-status:roaming:read

But when it comes to subscription endpoint (where either roaming or connectivity related event could be requested), there is somehow a common scope defined (which IMHO does not give the true picture): 
"device-status:subscriptions:create" 

And with this subscription any one of the below event types could be subscribed to:

- org.camaraproject.device-status.v0.roaming-status, 
- org.camaraproject.device-status.v0.roaming-on, 
- org.camaraproject.device-status.v0.roaming-off, 
- org.camaraproject.device-status.v0.roaming-change-country, 
- org.camaraproject.device-status.v0.connectivity-data, 
- org.camaraproject.device-status.v0.connectivity-sms, 
- org.camaraproject.device-status.v0.connectivity-disconnected, 
- org.camaraproject.device-status.v0.subscription-ends 

This seems to me like some sort of wildcard scope anyway. So when does one decide, that a different scope is needed?

**Comment by bigludo7** [comment]
Hello
To be sure to get your point @shilpa-padgaonkar 

Instead of:

```
  /subscriptions:
    post:
      tags:
        - Device status subscription
      summary: "Create a device status event subscription for a device"
      description: Create a device status event subscription for a device
      operationId: createDeviceStatusSubscription
      security:
        - openId:
            - device-status:subscriptions:create
```
We should have:

```
  /subscriptions:
    post:
      tags:
        - Device status subscription
      summary: "Create a device status event subscription for a device"
      description: Create a device status event subscription for a device
      operationId: createDeviceStatusSubscription
      security:
        - openId:
            - device-status:subscriptions:read-roaming-status
            - device-status:subscriptions:read-roaming-on
            - device-status:subscriptions:read-roaming-off
            - device-status:subscriptions:read-roaming-change-country
            - device-status:subscriptions:read-connectivity-data
            - device-status:subscriptions:read-connectivity-sms
            - device-status:subscriptions:read-connectivity-disconnected
```

Make sense indeed to manage the subscription 'topic' consent from the device user and not the fact that an application developer is authorized to perform the POST operation.

Do we need also specific scope for GET & DELETE /subscriptions.... I'm not sure about this. WDYT?
