### ISSUE TITLE
common.yaml unnecessarily list ErrorInfo properties as required.

### ISSUE THREAD

**Issue by gmuratk** [camaraproject/Commonalities#162]
**Problem description**

Assuming the language in API Design Guidelines is normative, CAMARA_common.yaml ErrorInfo format is incorrectly/unnencessarily requiring all the properties of ErrorInfo schema.
```
ErrorInfo:
   type: object
   required:
    - message
    - status
    - code
   properties:
    message:
     type: string
     description: A human readable description of what the event represent
    status:
     type: integer
     description: HTTP response status code
    code:
     type: string
     description: Friendly Code to describe the error
``` 

**Expected behavior**

Per DG, no field should be listed as required.

**Alternative solution**

Explicitly state which fields, if any, are required in Design Guideline and update, as necessary, the CAMARA_common.yaml to match definition.

**Additional context**
