### ISSUE TITLE
Add security to CAMARA_common.yaml

### ISSUE THREAD

**Issue by AxelNennker** [camaraproject/Commonalities#217]
**Problem description**
OpenAPI Specification allows APIs to describe their authentication and authorization requirements - their security requirements.
This is done by defining a [security scheme](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#security-scheme-object) that can than be [applied](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#security-requirement-object) to endpoints or to the API as a whole.

Commonly used security schemes of a Camara API should be in 
[CAMARA_common.yaml](https://github.com/camaraproject/Commonalities/blob/main/artifacts/CAMARA_common.yaml)

**Expected action**
The IdentityAndConsent WG developed one security scheme for OpenId Connect.

```yaml
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
```

This should be added to CAMARA_common.yaml and probably applied to the API as a whole.
