### ISSUE TITLE
Adding `SUBSCRIPTION_DELETED` as a `terminationReason` [event-subscription-template.yaml]

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/Commonalities#237]
**Problem description**
As of now we have the current valid values of `terminationReason`:

```yaml
    TerminationReason:
      type: string
      description: |
        - NETWORK_TERMINATED - API server stopped sending notification
        - SUBSCRIPTION_EXPIRED - Subscription expire time (optionally set by the requester) has been reached
        - MAX_EVENTS_REACHED - Maximum number of events (optionally set by the requester) has been reached
        - ACCESS_TOKEN_EXPIRED - Access Token sinkCredential (optionally set by the requester) expiration time has been reached
      enum:
        - MAX_EVENTS_REACHED
        - NETWORK_TERMINATED
        - SUBSCRIPTION_EXPIRED
        - ACCESS_TOKEN_EXPIRED
```

But we do not have a termination-reason when the Subscription was deleted by the User.

**Possible evolution**
Add `SUBSCRIPTION_DELETED` as a new `terminationReason`.

**Related Issues**
- https://github.com/camaraproject/Commonalities/issues/153
- https://github.com/camaraproject/Commonalities/issues/149
- https://github.com/camaraproject/DeviceLocation/issues/141
- https://github.com/camaraproject/DeviceStatus/issues/117
