### ISSUE TITLE
Add a note that `ACCESSTOKEN` is only supported for subscription-APIs

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/Commonalities#389]
**Problem description**
In the API design guidelines it's described, that the `credentialType` "MUST be set to `ACCESSTOKEN` for now".
I would like to add a `note` also in the `event-subscription-template.yaml` as there it's only mentioned in one of the HTTP-400-error-examples.

**Expected behavior**
Add a note in the template, like:

```yaml

SinkCredential: 
      description: A sink credential provides authentication or authorization information necessary to enable delivery of events to a target.
      type: object
      properties:
        credentialType:
          type: string
          enum:
            - PLAIN
            - ACCESSTOKEN
            - REFRESHTOKEN
          description: | 
            The type of the credential. 
            Note: Type of the credential - MUST be set to ACCESSTOKEN for now
```
