### ISSUE TITLE
Add a note if registered JWT claim "exp" is given - must match with property "accessTokenExpiresUtc"

### ISSUE THREAD

**Issue by dfischer-tech** [camaraproject/Commonalities#401]
**Problem description**
In general, I am fine with the parameter **"accessTokenExpiresUtc"**. 
However, in most cases, the expiration time of the token is also provided in the "exp" claim. [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519#page-9)

Since this registered claim is not mandatory, it should, if present, at least match the value of **"accessTokenExpiresUtc"**. 
Otherwise, the request should return a 400 - INVALID_ARGUMENT error.

**Expected behavior**
Add a note in the template, like:
```yaml
    AccessTokenCredential:
      type: object
      description: An access token credential.
      allOf:
        - $ref: "#/components/schemas/SinkCredential"
        - type: object
          properties:
            accessToken:
              description: REQUIRED. An access token is a previously acquired token granting access to the target resource.
              type: string
            accessTokenExpiresUtc:
              type: string
              format: date-time
              description: |
                REQUIRED. An absolute UTC instant at which the token shall be considered expired.
                If the registered "exp" (Expiration Time) claim is present, it must match the expiration time specified in the token.
            accessTokenType:
              description: REQUIRED. Type of the access token (See [OAuth 2.0](https://tools.ietf.org/html/rfc6749#section-7.1)).
              type: string
              enum:
                - bearer
          required:
            - accessToken
            - accessTokenExpiresUtc
            - accessTokenType
```

Additional note:
It would be highly beneficial to transmit the value in Unix-Timestamp format.
Example:
```yaml
        accessTokenExpiresUtc:
          description: |
            REQUIRED. The Unix timestamp representing the absolute UTC instant at which the token shall be considered expired.
            If the registered "exp" (Expiration Time) claim is present, it must match the expiration time specified in the token.
          type: integer
          format: int64
```

What do you think?

**Comment by eric-murray** [comment]
Hi @dfischer-tech
> However, in most cases, the expiration time of the token is also provided in the "exp" claim. [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519#page-9)

I take your point, but I'd been expecting that "in most cases" the token would be opaque. I'm curious to know why do you think JWTs will be the normal case for event notifications.

**Comment by dfischer-tech** [comment]
Hi, @eric-murray, 
Thank you for your interest in my explanation.
The expression I used, "in most cases," referred to the use of the registered claim "exp" in a token. Specifically, when a client subscribes to event notifications and uses the optional 'SinkCredential' with 'ACCESSTOKEN', the interoperable "exp" claim in the token is not mandatory, but rather recommended.
My recommendation is that if the claim is present, it should match the parameter.

**Comment by eric-murray** [comment]
The temptation will be for API providers to treat the token as opaque, even if it is a JWT.

I can see that IF the token is a JWT and IF it contains the `exp` claim, THEN a check can be made that this matches the `accessTokenExpiresUtc` parameter.

The question is whether these two pre-conditions would be true often enough for an API provider to consider that such a check would be worth implementing. If it's going to be rare, then just leave it up to API providers to decide what checks they will do.

**Comment by eric-murray** [comment]
@sachinvodafone 
If the API provider can read the JWT, then so can the API consumer before they send it. They should then adjust `accessTokenExpiresUtc` if it does not match the JWT `exp` claim. If that claim is present, I'd expect that to be the true token expiration time (an authorisation server that does not respect it's own token expiration times is not much of an authorisation server).

However, I think it should be left up to the API provider what checks they perform. If a notification fails because the token has expired despite the `accessTokenExpiresUtc` saying it should still be valid, well that's really the API consumer's problem - the notification was still sent.

**Comment by dfischer-tech** [comment]
Okay, I agree with leaving it up to the API providers to decide which validations they want to enforce.

If an API provider wants to prevent requests from the API consumer regarding missing "event notifications" or why no "subscription-ends" notification was received - based on the case where the expiration time of the Access Token SinkCredential (optionally set by the requester) has been reached, then they should incorporate such validations.

My suggestion would be to simply adjust the note from "must" to "should".
```yaml
            accessTokenExpiresUtc:
              type: string
              format: date-time
              description: |
                REQUIRED. An absolute UTC instant at which the token shall be considered expired.
                If the registered "exp" (Expiration Time) claim in the token is present, it should match.
 ```

What do you think about my additional remark: "to transmit the value in Unix-Timestamp format"?
```yaml
        accessTokenExpiresUtc:
          description: |
            REQUIRED. The Unix timestamp representing the absolute UTC instant at which the token shall be considered expired.
            If the registered "exp" (Expiration Time) claim in the token is present, it should match.
          type: integer
          format: int64
```
Thank you for your interest. If you do not share my recommendation, feel free to close this issue.
