### ISSUE TITLE
[event-subscription-template]: invalid `url`-format for the `sink`

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/Commonalities#420]
**Problem description**
The [event-subscription-template](https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml#L482) has an invalid format `url` for the `sink` in the `Subscription`-response component.

```yaml
    Subscription:
      description: Represents a event-type subscription.
      type: object
      required:
        - sink
        - protocol
        - config
        - types
        - id
      properties:
<...>
        sink:
          type: string
          format: url
          description: The address to which events shall be delivered using the selected protocol.
          example: "https://endpoint.example.com/sink"
```

**Expected behavior**
The format should be `uri`.
```yaml
        sink:
          type: string
          format: uri
          description: The address to which events shall be delivered using the selected protocol.
          example: "https://endpoint.example.com/sink"
```
