### ISSUE TITLE
Add a `type`-check for the linting-rules

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/Commonalities#433]
**Problem description**
In SimSwap we discovered that there was a property defined without having the `type`-attribute set.
See https://github.com/camaraproject/SimSwap/issues/195

**Possible evolution**
Add a spectral-rule for checking the `type`-attribute.

e.g.

```yaml
camara-schema-type-check:
  message: "Invalid or missing type in schema definition."
  severity: error
  given: "$.components.schemas.*"
  then:
    field: type
    function: pattern
    functionOptions:
      match: "^(string|number|integer|boolean|array|object)$"
  recommended: true
```
