### ISSUE TITLE
Arrays of types (SubscriptionEventType) are still restricted to one within CAMARA-API-Event-Subscription-and-Notification-Guide.md?

### ISSUE THREAD

**Issue by hdamker** [camaraproject/Commonalities#460]
**Problem description**

I understood from #432 that APIs can now decide to allow to pass more than one SubscriptionEventType within a subscription request. But the following line

https://github.com/camaraproject/Commonalities/blob/29cd5d3a53c04f74948db6755c99daa925c1ffa0/documentation/CAMARA-API-Event-Subscription-and-Notification-Guide.md?plain=1#L144

still states that it MUST be only one, and the use of multiple values will be open only "later" at API level:

> Note: An array of types could be passed **but as of now only one value MUST passed**. Use of multiple value will be open later at API level.

**Expected behavior**

The current formulation is at least ambiguous and might be better aligned with the template which states "Note: the maximum number of event types per subscription will be decided at API project level".

**Alternative solution**

**Additional context**

**Comment by PedroDiez** [comment]
As commented in Commonalities Meeting 12/May, besides this wording alignment we can make an additional action (checked and the other one is already considered) in order to avoid further discussions about this item and their understading.
cc @rartych @patrice-conil 

Updates in [event-subscription-template.yaml](https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml)

- Remove maxItems: https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml#L291 / https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml#L492. Therefore the template does not restrict it and it is up to the specific WG to make such a restriction in case it is wanted to explicitly keep to one event so far as no make sense the multiple events Use Case so far.
- As exception in POST /subscriptions 422 - MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED is already defined, this provides flexibility for Operators when API definition does not explicitly restricts the maximum number of event types to 1.

**Comment by maxl2287** [comment]
Hi,

I have a general question, when an API supports multiple `types`.

For example, due to limitations in the network, `roaming-change-country` (DeviceRoamingSubscriptions) might not be supported or might be temporarily non-functional, but `roaming-on` is supported.

Could you please clarify what the expected behavior is in such a case, when a CAMARA subscription is "partially" active?

Specifically:

Should the subscription request be rejected entirely (e.g. with a 400 Bad Request) if one or more of the requested types are unsupported? Or a `422 Unprocessable Entity`?

Or should it be accepted partially, and if so, how should the response indicate which types were actually accepted?

Is there a recommended way for clients to discover supported types before making the request?

This clarification is important to avoid situations where clients believe they are subscribed to events that will never be delivered, leading to silent failures.

cc @hdamker @rartych

**Comment by rartych** [comment]
As the intention of API Consumer could be using multiple event types in their service logic (one event type is not sufficient) , the simplest approach is to reject the request.  

Currently in the [template](https://github.com/camaraproject/Commonalities/blob/main/artifacts/camara-cloudevents/event-subscription-template.yaml#L1124) we have:

```
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              description: Service not applicable for the provided identifier
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not available for the provided identifier.
```

It can be modified to cover this case or new one can be added like:

```
           GENERIC_422_MULTIEVENT_COMBINATION_NOT_SUPPORTED:
              description: Combination of multiple event types is not supported
              value:
                status: 422
                code: MULTIEVENT_COMBINATION_NOT_SUPPORTED
                message: Requested combination of multiple event types is not supported
```
