### ISSUE TITLE
Specify string format whenever possible

### ISSUE THREAD

**Issue by patrice-conil** [camaraproject/Commonalities#93]
**Problem description**
As in [geofencing](https://github.com/camaraproject/DeviceLocation/issues/118), I propose to constrain the string format whenever possible to simply implementation and clarify usage.

For example, everywhere we use notification :Geolocation, Qod, DeviceStatus and SimSwap ...
```yaml
    NotificationUrl:
      type: string
      example: "https://application-server.com"
      description: https callback address where the event notification must be POST-ed
```
Would be
```yaml
    NotificationUrl:
      type: string
      format: uri
      example: "https://application-server.com"
      description: https callback address where the event notification must be POST-ed
```
**Expected action**
Add paragraph in guidelinse to describe this
